#!/bin/sh

if test -z "`which rustc`" -o -z "`rustc +nightly -V 2>/dev/null`"; then
    echo "Nightly Rust does not appear to be properly installed."
    exit 1
fi

cd "`dirname \"$0\"`" || exit 1

name="nether"

echo "Compiling $name for testing..."
rustc +nightly --edition 2021 --test -o test-harness src/main.rs || exit 1
./test-harness "$@" || exit 1
